server:
  port: 8080
  address: 0.0.0.0
#
#app:
#  service-prefix:
#    account: /account
springdoc:
  swagger-ui:
    urls:
      - name: Account Service
        url: /account-service/v3/api-docs
      - name: Service B
        url: /service-b/v3/api-docs

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        # 8801
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=${app.api-prefix}${app.service-prefix.auth}/**
          filters:
            - RewritePath=${app.api-prefix}${app.service-prefix.auth}/(?<segment>.*), /${segment}


eureka:
  client:
    service-url:
      defaultZone: http://eureka:123456@localhost:8761/eureka