server:
  context-path: /brand-service
  port: 8082
spring:
  application:
    name: brand-service
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
  springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
